### ISSUE TITLE
one of the entries in efo_labels needs whitespace trimming

### ISSUE THREAD

**Issue by rgentlem** [ccb-hms/openGWASSearchDB#4]
I see this warning:
In transparent_trim(x[[cname]], remember_spaces) :
  Leading and trailing whitespace has been trimmed for 1 texts. 

 So I think that means that I will have trouble selecting it, if I get the label from the efo_labels table...

**Comment by rsgoncalves** [comment]
This should be solved now and closed via commit d0b213c.
